AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack template

Parameters:
  VpcCIDR:
    Type: String
  vpcname:
    Type: String
Resources:

   NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/worley-nc-deployment/vpc.yml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        vpcname: !Ref vpcname
