AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Main stack template

Parameters:
  VpcCIDR:
    Type: String
  Name:
    Type: String
  EnvironmentName:
    Type: String

Resources:

  NestedVPCStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: 'https://s3.amazonaws.com/worley-nc-deployment/vpc.yaml'
      Parameters:
        Name: !Ref Name
        VpcCIDR: !Ref VpcCIDR
        EnvironmentName: !Ref EnvironmentName
