AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to Create CloudTrail with S3 Data Events

Parameters:
  TrailName:
    Type: String
  S3BucketCTName:
    Type: String
    
Resources:
  S3BucketCT:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketCTName

  S3BucketCTPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketCT
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudTrail
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub "arn:aws:s3:::${S3BucketCTName}/*"
          - Sid: AllowGetBucketAcl
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !Sub "arn:aws:s3:::${S3BucketCTName}"

  CloudTrailLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "/aws/cloudtrail/${AWS::StackName}"
      RetentionInDays: 90

  CloudTrailRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudTrailPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetBucketAcl'
                Resource:
                  - !Sub "arn:aws:s3:::${S3BucketCTName}/*"
                  - !Sub "arn:aws:s3:::${S3BucketCTName}"
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/cloudtrail/${AWS::StackName}:*"

  CloudTrail:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref S3BucketCTName
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailRole.Arn
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      IsLogging: true
      EventSelectors:
        - DataResources:
            - Type: "AWS::S3::Object"
              Values:
                - !Sub "arn:aws:s3:::${AWS::AccountId}-mmy-demo-nw/"
          IncludeManagementEvents: false
          ReadWriteType: All

Outputs:
  CloudTrailName:
    Description: "Name of the CloudTrail"
    Value: !Ref CloudTrail

  CloudTrailBucket:
    Description: "S3 Bucket for CloudTrail logs"
    Value: !Ref S3BucketCT

  CloudTrailLogGroup:
    Description: "CloudWatch Log Group for CloudTrail logs"
    Value: !Ref CloudTrailLogGroup