AWSTemplateFormatVersion: "2010-09-09"
Description: ECR stack template

Parameters:
  repoNameUI: 
    Description: Name for ecr repo 
    Type: String

Resources:
  ecrRepoUI:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${repoNameUI}-repo
      ImageScanningConfiguration: 
        ScanOnPush: true
Outputs:
  ecrRepoName:
      Description: "The name of the S3 bucket."
      Value: !Ref ecrRepoUI
      Export:
        Name: !Sub ${repoNameUI}-repo