AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Parameters:

  VpcName:
    Type: String
  S3BucketName:
    Type: String

  TrafficType:
    Description: 'The type of traffic to log.'
    Type: String
    Default: ALL
    AllowedValues:
      - ACCEPT
      - REJECT
      - ALL

Resources:

  MyFlowLogDeliveringToS3:
    Type: AWS::EC2::FlowLog
    Properties: 
      ResourceId: !ImportValue 
        Fn::Sub: "${VpcName}-VpcId"
      ResourceType: VPC
      TrafficType: !Ref TrafficType
      LogDestination: !Sub 'arn:aws:s3:::${S3BucketName}/vpc-flow-logs/'
      LogDestinationType: s3
      LogFormat: ${version} ${vpc-id} ${subnet-id} ${instance-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${tcp-flags} ${type} ${pkt-srcaddr} ${pkt-dstaddr}
      MaxAggregationInterval: 60
      DestinationOptions:
        FileFormat: parquet
        HiveCompatiblePartitions: true
        PerHourPartition: true
      Tags:
        - Key: Name
          Value: FlowLogForSubnetB
        - Key: Purpose
          Value: AcceptTraffic