AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Parameters:


  S3BucketName:
    Type: String
  MySubnet:
    Type: String
Resources:
  MyFlowLogDeliveringToS3:
      Type: AWS::EC2::FlowLog
      Properties: 
        ResourceId: !Ref MySubnet
        ResourceType: Subnet
        TrafficType: ACCEPT
        LogDestination: !GetAtt S3BucketName.Arn
        LogDestinationType: s3
        LogFormat: ${version} ${vpc-id} ${subnet-id} ${instance-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${tcp-flags} ${type} ${pkt-srcaddr} ${pkt-dstaddr}
        MaxAggregationInterval: 60
        DestinationOptions:
          FileFormat: parquet
          HiveCompatiblePartitions: true
          PerHourPartition: true
        Tags:
          - Key: Name
            Value: FlowLogForSubnetB
          - Key: Purpose
            Value: AcceptTraffic

  

Outputs:
  VPCFlowLogId:
    Description: 'The ID of the VPC Flow Log'
    Value: !Ref VPCFlowLog
    Export:
      Name: !Sub '${Name}-vpc-flow-log-id'

